# Generated by Django 5.2.1 on 2025-05-29 15:19

import apps.rent.choices.room_type
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=170)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms_count', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(choices=apps.rent.choices.room_type.RoomType.choices, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
